swagger: "2.0"
info:
  description: "A send email API server for interfacing with the Zoho Mail API"
  version: "1.0.0"
  title: "Zoho Send Email API"
host: "localhost:3000"
basePath: "/api/v1"
tags:
- name: "General"
schemes:
- "http"
paths:
  /message:
    post:
      tags:
      - "General"
      summary: "Send an HTML email message"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "New message content"
        required: true
        schema:
          $ref: "#/definitions/MessageInfo"
      responses:
        200:
          description: "Queued to send"
        400:
          description: "Invalid input provided"
          schema:
            $ref: "#/definitions/ErrorPacket"
        401:
          description: "Not authorized to access the server"
      security:
      - api_key: []
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "Authorization"
    in: "header"
definitions:
  ErrorPacket:
    type: "object"
    required:
    - "message"
    properties:
      message:
        type: "string"
        example: "You must provide an email address"
  MessageInfo:
    type: "object"
    required:
    - "from"
    - "to"
    - "content"
    properties:
      from:
        type: "string"
        example: "jim@email.com"
      to:
        type: "string"
        example: "britney@domain.com"
      cc:
        type: "string"
        example: "boss@corporate.com"
      bcc:
        type: "string"
        example: "hidden@tracking.com"
      subject:
        type: "string"
        example: "Friendly Reminder for Tomorrow"
      content:
        type: "string"
        description: "HTML content body. No new line characters permitted"
        example: "Some serious content<br>Woah, does this make sense?"
