version: "3"
services:
  # NODE API
  node:
    image: "node:lts-alpine"
    user: node
    restart: always
    working_dir: /home/node/app
    volumes:
      - ./node:/home/node/app
    ports:
      - 3000:3000
    command: "npm run dev"
  swagger:
    image: swaggerapi/swagger-ui
    restart: always
    depends_on:
      - node
    ports:
      - 8081:8080
    volumes:
      - ./design:/data
    environment:
      SWAGGER_JSON: /data/api.yaml
volumes:
  dbdata:
    driver: local
