version: "3"
services:
  # NODE API
  testnode:
    image: "node:lts-alpine"
    user: node
    working_dir: /home/node/app
    volumes:
      - ./node:/home/node/app
    networks:
      - testing
    environment:
      NODE_ENV: test
    command: "npm test"

networks:
  testing:
